# Wildcard labels
brace_expansion: true
extended_glob: true

rules:
  - labels: [infrastructure]
    patterns: ['*|{tools,requirements,.github}/**|-README.md']

  - labels: [source]
    patterns: ['pymdownx/**']

  - labels: [tests]
    patterns: ['tests/**']

  - labels: [docs]
    patterns: ['docs/**|README.md']

  - labels: [caret]
    patterns: ['**/?(test_)caret*|**/caret/**']

  - labels: [arithmatex]
    patterns: ['**/?(test_)arithmatex*|**/arithmatex/**']

  - labels: [critic]
    patterns: ['**/?(test_|gen_)critic*|**/critic/**']

  - labels: [details]
    patterns: ['**/?(test_)details*|**/details/**']

  - labels: [emoji]
    patterns: ['**/?(test_|gen_)emoji*|**/emoji/**|pymdownx/{gemoji,emoji1,twemoji}_db.py']

  - labels: [escapeall]
    patterns: ['**/?(test_)escapeall*|**/escapeall/**']

  - labels: [extra]
    patterns: ['**/?(test_)extra!(rawhtml)*|**/extra/**|-docs/theme/**|-docs/src/@(js|scss)/**']

  - labels: [extrarawhtml]
    patterns: ['**/?(test_)extrarawhtml*|**/extrarawhtml/**']

  - labels: [highlight]
    patterns: ['**/?(test_)highlight*|**/highlight/**']

  - labels: [inlinehilite]
    patterns: ['**/?(test_)inlinehilite*|**/inlinehilite/**']

  - labels: [keys]
    patterns: ['**/?(test_)keys*|**/keys/**|pymdownx/keymap_db.py']

  - labels: [magiclink]
    patterns: ['**/?(test_)magiclink*|**/magiclink/**']

  - labels: [mark]
    patterns: ['**/?(test_)mark*|**/mark/**']

  - labels: [pathconverter]
    patterns: ['**/?(test_)pathconverter*|**/pathconverter/**']

  - labels: [progressbar]
    patterns: ['**/?(test_)progressbar*|**/progressbar/**']

  - labels: [slugs]
    patterns: ['**/?(test_)slugs*|**/slugs/**']

  - labels: [smartsymbols]
    patterns: ['**/?(test_)smartsymbols*|**/smartsymbols/**']

  - labels: [snippets]
    patterns: ['**/?(test_)snippets*|**/snippets/**']

  - labels: [striphtml]
    patterns: ['**/?(test_)striphtml*|**/striphtml/**']

  - labels: [superfences]
    patterns: ['**/?(test_)superfences*|**/superfences/**|**/_bypassnorm.py']

  - labels: [tasklist]
    patterns: ['**/?(test_)tasklist*|**/tasklist/**']

  - labels: [tilde]
    patterns: ['**/?(test_)tilde*|**/tilde/**']

# WIP
wip:
  - work-in-progress
  - needs-review
  - needs-decision
  - needs-confirmation
  - requires-changes
  - rejected

# Label management
delete_labels: true

colors:
    bug: '#c45b46'
    feature: '#7b17d8'
    support: '#efbe62'
    maintenance: '#b2ffeb'
    category: '#709ad8'
    subcategory: '#bfd4f2'
    pending: '#f0f49a'
    rejected: '#f7c7be'
    approved: '#beed6d'
    low: '#dddddd'

ignores:
  - dependencies
  - javascript
  - python
  - security

labels:
- name: bug
  color: bug
  description: Bug report.

- name: feature
  color: feature
  description: Feature request.

- name: maintenance
  color: maintenance
  description: Maintenance chore.

- name: support
  color: support
  description: Support request.

- name: docs
  color: category
  description: Related to documentation.

- name: tests
  color: category
  description: Related to testing.

- name: infrastructure
  color: category
  description: Related to project infrastructure.

- name: source
  color: category
  description: Related to source code.

- name: arithmatex
  color: subcategory
  description: Related to the arithmatex extension.

- name: b64
  color: subcategory
  description: Related to the b64 extension.

- name: betterem
  color: subcategory
  description: Related to the betterem extension.

- name: caret
  color: subcategory
  description: Related to the caret extension.

- name: critic
  color: subcategory
  description: Related to the critic extension.

- name: details
  color: subcategory
  description: Related to the details extension.

- name: emoji
  color: subcategory
  description: Related to the emoji extension.

- name: escapeall
  color: subcategory
  description: Related to the escapeall extension.

- name: extra
  color: subcategory
  description: Related to the extra extension.

- name: extrarawhtml
  color: subcategory
  description: Related to the extrarawhtml extension.

- name: highlight
  color: subcategory
  description: Related to the highlight extension.

- name: inlinehilite
  color: subcategory
  description: Related to the inlinehilite extension.

- name: keys
  color: subcategory
  description: Related to the keys extension.

- name: magiclink
  color: subcategory
  description: Related to the magiclink extension.

- name: mark
  color: subcategory
  description: Related to the mark extension.

- name: pathconverter
  color: subcategory
  description: Related to the paythconverter extension.

- name: progressbar
  color: subcategory
  description: Related to the progressbar extension.

- name: slugs
  color: subcategory
  description: Related to the slugs extension.

- name: smartsymbols
  color: subcategory
  description: Related to the smartsymbols extension.

- name: snippets
  color: subcategory
  description: Related to the snippets extension.

- name: striphtml
  color: subcategory
  description: Related to the striphtml extension.

- name: superfences
  color: subcategory
  description: Related to the superfences extension.

- name: tasklist
  color: subcategory
  description: Related to the tasklist extension.

- name: tilde
  color: subcategory
  description: Related to the tilde extension.

- name: triage
  color: pending
  description: Issue needs triage.

- name: more-info-needed
  color: pending
  description: More information is required.

- name: needs-confirmation
  color: pending
  description: The alleged behavior needs to be confirmed.

- name: needs-decision
  color: pending
  description: A decision needs to be made regarding request.

- name: confirmed
  color: approved
  description: Confirmed bug report or approved feature request.

- name: maybe
  color: low
  description: Pending approval of low priority request.

- name: duplicate
  color: rejected
  description: The issue has been previously reported.

- name: wontfix
  color: rejected
  description: The issue will not be fixed for the stated reasons.

- name: invalid
  color: rejected
  description: Invalid report (user error, upstream issue, etc).

- name: triage
  color: pending
  description: Issue needs triage.

- name: work-in-progress
  color: pending
  description: A partial solution. More changes will be coming.

- name: needs-review
  color: pending
  description: Needs to be reviewed and/or approved.

- name: requires-changes
  color: pending
  description: Awaiting updates after a review.

- name: approved
  color: approved
  description: The pull request is ready to be merged.

- name: rejected
  color: rejected
  description: The pull request is rejected for the stated reasons.
