template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels
brace_expansion: true
extended_glob: true
minus_negate: false

rules:
  - labels: ['C: infrastructure']
    patterns: ['*|@(requirements|.github)/**|!*.md']

  - labels: ['C: source']
    patterns: ['pymdownx/**']

  - labels: ['C: tests']
    patterns: ['tests/**']

  - labels: ['C: docs']
    patterns: ['docs/**|*.md']

  - labels: ['C: caret']
    patterns: ['**/?(test_)caret*.py|tests/**/caret/**']

  - labels: ['C: arithmatex']
    patterns: ['**/?(test_)arithmatex*.py|tests/**/arithmatex/**']

  - labels: ['C: critic']
    patterns: ['**/?(test_|gen_)critic*.py|tests/**/critic/**']

  - labels: ['C: details']
    patterns: ['**/?(test_)details*.py|tests/**/details/**']

  - labels: ['C: emoji']
    patterns: ['**/?(test_|gen_)emoji*|tests/**/emoji/**|pymdownx/@(gemoji|emoji1|twemoji)_db.py']

  - labels: ['C: escapeall']
    patterns: ['**/?(test_)escapeall*.py|tests/**/escapeall/**']

  - labels: ['C: extra']
    patterns: ['**/?(test_)extra!(rawhtml)*.py|tests/**/extra!(rawhtml)/**|!docs/theme/**|!docs/src/@(js|scss)/**']

  - labels: ['C: extrarawhtml']
    patterns: ['**/?(test_)extrarawhtml*.py|tests/**/extrarawhtml/**']

  - labels: ['C: highlight']
    patterns: ['**/?(test_)highlight*.py|tests/**/highlight/**']

  - labels: ['C: inlinehilite']
    patterns: ['**/?(test_)inlinehilite*.py|tests/**/inlinehilite/**']

  - labels: ['C: keys']
    patterns: ['**/?(test_)keys*.py|tests/**/keys/**|pymdownx/keymap_db.py']

  - labels: ['C: magiclink']
    patterns: ['**/?(test_)magiclink*.py|tests/**/magiclink/**']

  - labels: ['C: mark']
    patterns: ['**/?(test_)mark*.py|tests/**/mark/**']

  - labels: ['C: pathconverter']
    patterns: ['**/?(test_)pathconverter*.py|tests/**/pathconverter/**']

  - labels: ['C: progressbar']
    patterns: ['**/?(test_)progressbar*.py|tests/**/progressbar/**']

  - labels: ['C: slugs']
    patterns: ['**/?(test_)slugs*.py|tests/**/slugs/**']

  - labels: ['C: smartsymbols']
    patterns: ['**/?(test_)smartsymbols*.py|tests/**/smartsymbols/**']

  - labels: ['C: snippets']
    patterns: ['**/?(test_)snippets*.py|tests/**/snippets/**']

  - labels: ['C: striphtml']
    patterns: ['**/?(test_)striphtml*.py|tests/**/striphtml/**']

  - labels: ['C: superfences']
    patterns: ['**/?(test_)superfences*.py|tests/**/superfences/**|**/_bypassnorm.py']

  - labels: ['C: tasklist']
    patterns: ['**/?(test_)tasklist*.py|tests/**/tasklist/**']

  - labels: ['C: tilde']
    patterns: ['**/?(test_)tilde*.py|tests/**/tilde/**']

ignores:
  - dependencies
  - javascript
  - security

labels:
- name: 'C: arithmatex'
  renamed: arithmatex
  color: subcategory
  description: Related to the arithmatex extension.

- name: 'C: b64'
  renamed: b64
  color: subcategory
  description: Related to the b64 extension.

- name: 'C: betterem'
  renamed: betterem
  color: subcategory
  description: Related to the betterem extension.

- name: 'C: caret'
  renamed: caret
  color: subcategory
  description: Related to the caret extension.

- name: 'C: critic'
  renamed: critic
  color: subcategory
  description: Related to the critic extension.

- name: 'C: details'
  renamed: details
  color: subcategory
  description: Related to the details extension.

- name: 'C: emoji'
  renamed: emoji
  color: subcategory
  description: Related to the emoji extension.

- name: 'C: escapeall'
  renamed: escapeall
  color: subcategory
  description: Related to the escapeall extension.

- name: 'C: extra'
  renamed: extra
  color: subcategory
  description: Related to the extra extension.

- name: 'C: extrarawhtml'
  renamed: extrarawhtml
  color: subcategory
  description: Related to the extrarawhtml extension.

- name: 'C: highlight'
  renamed: highlight
  color: subcategory
  description: Related to the highlight extension.

- name: 'C: inlinehilite'
  renamed: inlinehilite
  color: subcategory
  description: Related to the inlinehilite extension.

- name: 'C: keys'
  renamed: keys
  color: subcategory
  description: Related to the keys extension.

- name: 'C: magiclink'
  renamed: magiclink
  color: subcategory
  description: Related to the magiclink extension.

- name: 'C: mark'
  renamed: mark
  color: subcategory
  description: Related to the mark extension.

- name: 'C: pathconverter'
  renamed: pathconverter
  color: subcategory
  description: Related to the paythconverter extension.

- name: 'C: progressbar'
  renamed: progressbar
  color: subcategory
  description: Related to the progressbar extension.

- name: 'C: slugs'
  renamed: slugs
  color: subcategory
  description: Related to the slugs extension.

- name: 'C: smartsymbols'
  renamed: smartsymbols
  color: subcategory
  description: Related to the smartsymbols extension.

- name: 'C: snippets'
  renamed: snippets
  color: subcategory
  description: Related to the snippets extension.

- name: 'C: striphtml'
  renamed: striphtml
  color: subcategory
  description: Related to the striphtml extension.

- name: 'C: superfences'
  renamed: superfences
  color: subcategory
  description: Related to the superfences extension.

- name: 'C: tasklist'
  renamed: tasklist
  color: subcategory
  description: Related to the tasklist extension.

- name: 'C: tilde'
  renamed: tilde
  color: subcategory
  description: Related to the tilde extension.
