strictness: medium
doc-warnings: true
test-warnings: false
max-line-length: 120
ignore-patterns:
  - build
  - node_modules
dodgy:
  run: false
pep257:
  disable:
    - D202
pylint:
  disable:
    - import-error
