# Document HTML files or folders of HTML files to search
# Files are relative to the CWD, not the config file itself.
docs:
- site

# Dictionary of words to ignore
dictionary:
- API
- Arithmatex
- BetterEm
- Bitbucket
- CDN
- CDNs
- CSS
- Changelog
- Cloudflare
- CodeHilite
- CodeHilite's
- CriticMarkup
- Ctrl
- Emoji
- EmojiOne
- EmojiOne's
- Esc
- EscapeAll
- ExtraRawHTML
- Fn
- GFM
- GIF
- Gemoji
- Gemoji's
- GitHub
- GitHub's
- GitHubEmoji
- GitLab
- GitLab's
- HeaderAnchor
- HeaderAnchor's
- Inline
- InlineHilite
- InlineHilite's
- JPEG
- JSON
- JavaScript
- KaTeX
- KBD
- LaTeX
- Limberg
- MERCHANTABILITY
- MagicLink
- MathJax
- MkDocs
- Mkdoc's
- NONINFRINGEMENT
- Num
- OAuth
- Octicons
- PHP
- PNG
- PNGs
- Pandoc
- PathConverter
- PlainHTML
- ProgressBar
- PyMdown
- PyMdown's
- Pygments
- SCSS
- SVG
- SVGs
- Slugify
- SmartSymbols
- StripHTML
- Stylesheets
- SuperFences
- Tasklist
- Toc
- Tox
- Twemoji
- Twitter's
- UML
- UTF
- Virtualenv
- Waylan
- YAML
- backrefs
- backtick
- backticks
- blockquote
- blockquotes
- bool
- builtins
- cmd
- coveragepy
- customizable
- dev
- dict
- docstrings
- ebeweber
- emoji
- emojione
- escaper
- facelessuser
- formatter
- gemoji
- gfm
- gforcada
- github
- highlighter's
- html
- inline
- ish
- jQuery
- js
- kbd
- linkafies
- linter
- lowercased
- lowercases
- md
- mkdocs
- mrab
- mrabarnett
- namespace
- nd
- ned
- nl
- online
- plugin
- plugins
- plusminus
- polyfill
- polyfilled
- polyfills
- pre
- prepend
- prepended
- prepending
- prepends
- preprocessor
- px
- py
- pycqa
- pymdown
- pypi
- pytest
- raphael
- regex
- reinstalling
- repo
- requesters
- revisioned
- sanitizer
- shortener
- shortname
- shortnames
- slugify
- squidfunk
- stylesheet
- stylesheets
- sublicense
- syntaxes
- th
- thumbsup
- tox
- uc
- un
- underscore's
- unicode
- uslugify
- versa
- whitespace

# Attributes of tags to also spell check along with tag content
attributes:
- title
- alt

# Selectors describing tags to ignore (tag, class, and/or id only)
ignores:
- code
- pre
- script
- style
- a.magiclink-compare
- a.magiclink-commit
- .MathJax_Preview
- .md-nav__link
- .md-footer-custom-text
- .md-source__repository
