documents:
- name: mkdocs
  filters:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
      - a.magiclink-compare
      - a.magiclink-commit
      - span.keys
      - .MathJax_Preview
      - .md-nav__link
      - .md-footer-custom-text
      - .md-source__repository
      - .headerlink
      - .md-icon
  sources:
  - site/**/*.html
  aspell:
    lang: en
  dictionary:
    lang: en
    wordlists:
    - docs/src/dictionary/en-custom.txt
    output: build/dictionary/mkdocs.dic

- name: markdown
  sources:
  - README.md
  aspell:
    lang: en
  dictionary:
    lang: en
    wordlists:
    - docs/src/dictionary/en-custom.txt
    output: build/dictionary/mkdocs.dic
  filters:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre

- name: javascript
  filters:
  - pyspelling.filters.javascript:
      jsdocs: true
  default_encoding: utf-8
  sources:
  - docs/src/js/*.js
  aspell:
    lang: en
  dictionary:
    lang: en
    wordlists:
    - docs/src/dictionary/en-custom.txt
    - docs/src/dictionary/en-javascript.txt
    output: build/dictionary/javascript.dic

- name: python
  sources:
  - pymdownx/**/*.py
  - tests/**/*.py
  - tools/**/*.py|!tools/tags/*
  aspell:
    lang: en
  dictionary:
    lang: en
    wordlists:
    - docs/src/dictionary/en-custom.txt
    - docs/src/dictionary/en-python.txt
    output: build/dictionary/python.dic
  filters:
  - pyspelling.filters.python:
      comments: false
      strings: false
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: \\[\\`~]
      delimiters:
        - open: (?P<open>`+)
          content: .*?
          close: (?P=open)
        - open: (?s)^(?P<open>\s*~{3,})
          content: .*?
          close: ^(?P=open)$
