[build-system]
requires = [
    "hatchling>=1.26",
]
build-backend = "hatchling.build"

[project]
name = "pymdown-extensions"
description = "Extension pack for Python Markdown."
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [
    { name = "Isaac Muse", email = "Isaac.Muse@gmail.com" },
]
keywords = [
    "extensions",
    "markdown",
]
dynamic = [
    "classifiers",
    "version",
]

dependencies = [
    "Markdown>=3.6",
    "pyyaml"
]

[project.urls]
Homepage = "https://github.com/facelessuser/pymdown-extensions"

[tool.hatch.version]
source = "code"
path = "pymdownx/__meta__.py"

[tool.hatch.metadata]
allow-direct-references = true

[project.optional-dependencies]
extra = [
    "Pygments>=2.19.1"
]

[tool.hatch.build.targets.sdist]
include = [
    "/docs/src/markdown/**/*.md",
    "/docs/src/markdown/**/*.gif",
    "/docs/src/markdown/**/*.png",
    "/docs/src/markdown/dictionary/*.txt",
    "/docs/theme/**/*.css",
    "/docs/theme/**/*.js",
    "/docs/theme/**/*.html",
    "/docs/theme/**/*.css.map",
    "/docs/theme/**/*.js.map",
    "/requirements/*.txt",
    "/pymdownx/**/*.py",
    "/tests/**/*.txt",
    "/tests/**/*.py",
    "/tests/**/*.html",
    "/tests/**/*.yml",
    "/tests/**/*.css",
    "/tests/**/*.png",
    "/tools/__init__.py",
    "/tools/pymdownx_md_render.py",
    "/.pyspelling.yml",
    "/.coveragerc",
    "/zensical.yml",
    "/run_tests.py"
]

[tool.hatch.build.targets.wheel]
include = [
    "/pymdownx",
]

[tool.hatch.metadata.hooks.custom]

[tool.mypy]
files = [
    "pymdownx/blocks/block.py"
]
strict = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "pymdownx.superfences"
]
ignore_errors = true

[tool.ruff]
line-length = 120

extend-exclude = [
    "build/*",
    ".tox/*",
    "site/*",
    "tools/tags/*",
    "node_modules/*",
    "*_db.py",
    "dist/*"
]

lint.select = [
    "A",    # flake8-builtins
    "B",    # flake8-bugbear
    "D",    # pydocstyle
    "C4",   # flake8-comprehensions
    "N",    # pep8-naming
    "E",    # pycodestyle
    "F",    # pyflakes
    "PGH",  # pygrep-hooks
    "RUF",  # ruff
    # "UP",   # pyupgrade
    "W",    # pycodestyle
    "YTT",  # flake8-2020,
    "PERF"  # Perflint
]

lint.ignore = [
    "E741",
    "D202",
    "D401",
    "D417",
    "D212",
    "D203",
    "N802",
    "N801",
    "N803",
    "N806",
    "N813",
    "N818",
    "RUF012",
    "RUF005"
]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    "pragma: no cover",
    "@overload"
]

[tool.hatch.envs.dev]
dependencies = [
    "pytest",
    "pytest-cov",
    "coverage",
    "mypy",
    "ruff",
    "build",
    "markdown>=3.6",
    "PyYAML>=3.10",
    "types-markdown>=3.10.2.20260712",
    "types-pyyaml>=6.0.12.20260815"
]

[tool.hatch.envs.docs]
dependencies = [
    "zensical",
    "markdown",
    "pymdown-extensions",
    "pymdown_lexers @ git+https://github.com/facelessuser/pymdown-lexers.git",
    "pyspelling",
    "build",
    "python-minifier"
]

[[tool.hatch.envs.dev.matrix]]
python = ["3.10", "3.11", "3.12", "3.13", "3.14"]

[[tool.hatch.envs.dev-stdlib.matrix]]
python = ["3.10", "3.11", "3.12", "3.13", "3.14"]

[tool.hatch.envs.dev.scripts]
types = "mypy"
tests = "pytest --cov pymdownx --cov-append --cov-report term-missing --cov-report xml --cov-report html:.cov tests"
lint = 'ruff check .'

[tool.hatch.envs.dev-stdlib.scripts]
tests = "pytest --cov pymdownx --cov-append --cov-report term-missing --cov-report xml --cov-report html:.cov tests"

[tool.hatch.envs.docs.scripts]
spellcheck = [
    "python -m zensical.main build -f zensical.yml --clean --strict; pyspelling -j 8"
]
clean = [
    "python -m zensical.main build -f zensical.yml --clean"
]
serve = [
    "python -m zensical.main serve -f zensical.yml"
]
build = [
    "python -m zensical.main build -f zensical.yml --clean"
]
