name: traige
on:
  issues:
    types: [opened]

jobs:
  triage:
    name: Add triage label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Apply Triage Label
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: label triage
